/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.airux.operationgenerator;

import ru.airux.operationgenerator.projectdirectory.ProjectDirectoryProviderFactory;
import ru.airux.operationgenerator.render.BaseRendererFactory;
import ru.airux.operationgenerator.render.BaseTemplateResolver;
import ru.airux.operationgenerator.writer.BaseCharWriterFactory;
import ru.airux.operationgenerator.writer.BaseFileCreator;

public class App {
    public static void main(String[] args) {
        String projectDirectory = ProjectDirectoryProviderFactory.getInstance().create(args).provide();
        System.out.println("Project directory: " + projectDirectory);

        OperationCreator creator = App.getOperationCreator(projectDirectory);
        getOperationsFactory().create(args).stream().forEach(creator::create);
        System.out.println("Done");
    }

    private static OperationCreator getOperationCreator(String projectDirectory) {
        return
                new BaseOperationCreator(
                        new BaseRendererFactory(),
                        new BaseTemplateResolver(),
                        new BaseCharWriterFactory(
                                new BaseFileCreator(
                                        System.getProperty("file.separator"),
                                        projectDirectory
                                )
                        )
                );
    }

    private static OperationsFactory getOperationsFactory() {
        return new ConsoleOperationsFactory(new ConsoleComponentFactory());
    }
}
